name: 'Bundlewatch Github Action - on Tracked Branches Push'

on:
  push:
    branches:
      - master

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Run BundleWatch Check
        uses: jackyef/bundlewatch-gh-action@0.1.0
        with:
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
