name: CI

on:
  pull_request:

env:
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}

jobs:
  mock-server:
    runs-on: ubuntu-latest
    name: Build the Docker image
    image: stefaniacardenas/onfido-web-sdk
    ports:
      - 8080:8080
    steps:
      - uses: actions/checkout@v2
        # run: |
        #   cd ./test/mock-server
        #   docker build . --file Dockerfile --tag stefaniacardenas/onfido-web-sdk:latest
        #   docker run -d --init --rm -p 8080:8080 stefaniacardenas/onfido-web-sdk:ui-mock-server
  build:
    runs-on: ubuntu-latest
    needs: [mock-server]
    strategy:
      matrix:
        include:
          - NODE_ENV: test
          # - NODE_ENV: production
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          # Match node version with .nvmrc
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        # TODO: Change this to use `npm ci`
        run: npm --production=false install
      # - name: Run NPM Audit
      #   run: audit-ci --moderate
      - name: Run UI Tests
        if: matrix.NODE_ENV == 'test'
        # uses: nanasess/setup-chromedriver@master
        run: npm run test:ui
          npm run test:integration
# after_success:
#   - python node_modules/travis-weigh-in/weigh_in.py dist/onfido.min.js
#   - chmod ugo+x ./deploy.sh
#   - ./deploy.sh

