name: CI

on:
  pull_request:

env:
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}

jobs:
  # Attempt 1: Runs the docker build correctly but the port is not exposed
  # mock-server:
  # runs-on: ubuntu-latest
  # steps:
  # - uses: actions/checkout@v2.3.4
  # - name: Build docker for mock server
  # run: |
  # cd ./test/mock-server
  # docker build -t onfido-web-sdk:ui-mock-server .
  # Attempt 2:
  # mock-server:
  #   runs-on: ubuntu-latest
  #   - name: Build the Docker image
  #     image: stefaniacardenas/onfido-web-sdk # This is the image on dockerhub, ideally we want to be using onfido-web-sdk:ui-mock-server
  #     ports:
  #       - 8080
  build:
    runs-on: ubuntu-latest
    # needs: [mock-server]
    strategy:
      matrix:
        include:
          - NODE_ENV: test
          # - NODE_ENV: production // renable this once the action works
    steps:
      - uses: actions/checkout@v2.3.4
      # Needed to be able to run `npm ci`. It fails if we try to install libraries from a github repo
      # e.g. "wpt": "git+https://github.com/Woopra/browser-tracker.git#v5.1.20",
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      ## Also tried to login to docker but it doesn't work
      # - name: Login to Docker Hub
      #   env:
      #       DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #       DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${DOCKER_HUB_USERNAME}
      #     password: ${DOCKER_HUB_ACCESS_TOKEN}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      # TODO:
      # - name: Run NPM Audit
      #   run: audit-ci --moderate
      - name: Build mock server
        if: matrix.NODE_ENV == 'test'
        run: |
          cd ./test/mock-server
          docker build -t onfido-web-sdk:ui-mock-server .
      - name: Run UI Tests
        if: matrix.NODE_ENV == 'test'
        run: |
          npm run test:ui
          # npm run test:integration

# TODO:
# after_success:
#   - python node_modules/travis-weigh-in/weigh_in.py dist/onfido.min.js
#   - chmod ugo+x ./deploy.sh
#   - ./deploy.sh
