# TODO: adjust when the CI job is executed

name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run dependencies audit
        uses: oke-py/npm-audit-action@v1.7.2
        with:
          audit_level: moderate
          production_flag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: kopijunkie
          issue_labels: vulnerability
          dedupe_issues: true

      - name: Run linters
        run: npm run check

      - name: Run build
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration
        env:
          SDK_TOKEN_FACTORY_SECRET: ${{ secrets.SDK_TOKEN_FACTORY_SECRET }}

      # TODO: we're building the whole sdk again with NODE_ENV=test, just because some properties e.g. MOBILE_URL are different.
      # We could skip this if this option can be passed as option while bootstrapping

      - name: Build test server
        run: npm run build:test
        id: testserver

      - name: Install Percy
        run: npm install -g @percy/cli

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run UI tests in Chrome
        working-directory: ./test/webtest
        id: chrome
        if: ${{ steps.testserver.outcome == 'success' }}
        # TODO: increase thread count, when we have more parallel sessions
        run: ./run-ui-tests.sh "-Dbrowser=chrome"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BUILD: ${{ github.ref }}-${{ github.run_id }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_JAVA }}

      - name: Publish Senelium Test Results - Chrome
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test/webtest/target/surefire-reports/junitreports/*.xml
          check_name: "UI Test results - Chrome"
          fail_on: "nothing"

      - name: Run UI tests in Firefox
        id: firefox
        if: ${{ steps.testserver.outcome == 'success' }}
        working-directory: ./test/webtest
        run: ./run-ui-tests.sh "-Dit.test=MultipleBrowsersDocumentUploadIT -Dbrowser=firefox"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BUILD: ${{ github.ref }}-${{ github.run_id }}

      - name: Publish Senelium Test Results - Firefox
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ steps.firefox.outcome == 'success' || steps.firefox.outcome == 'failure' }}
        with:
          files: test/webtest/target/surefire-reports/junitreports/*.xml
          check_name: "UI Test results - Firefox"
          fail_on: "nothing"

      - name: Run UI tests in Edge
        working-directory: ./test/webtest
        id: edge
        if: ${{ steps.testserver.outcome == 'success' }}
        run: ./run-ui-tests.sh "-Dit.test=MultipleBrowsersDocumentUploadIT -Dbrowser=edge"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BUILD: ${{ github.ref }}-${{ github.run_id }}

      - name: Publish Senelium Test Results - Edge
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ steps.edge.outcome == 'success' || steps.edge.outcome == 'failure' }}
        with:
          files: test/webtest/target/surefire-reports/junitreports/*.xml
          check_name: "UI Test results - Edge"
          fail_on: "nothing"

      - name: Run UI tests in Safari
        working-directory: ./test/webtest
        id: safari
        if: ${{ steps.testserver.outcome == 'success' }}
        run: ./run-ui-tests.sh "-Dit.test=MultipleBrowsersDocumentUploadIT -Dbrowser=safari -DbrowserVersion=15.1"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BUILD: ${{ github.ref }}-${{ github.run_id }}

      - name: Publish Senelium Test Results - Safari
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ steps.safari.outcome == 'success' || steps.safari.outcome == 'failure' }}
        with:
          files: test/webtest/target/surefire-reports/junitreports/*.xml
          check_name: "UI Test results - Safari"
          fail_on: "nothing"

      - name: Verify test results
        if: ${{ steps.testserver.outcome == 'success' }}
        shell: bash
        run: |
          set -x

          CHROME=${{ steps.chrome.outputs.exit_code }}
          FIREFOX=${{ steps.firefox.outputs.exit_code }}
          EDGE=${{ steps.edge.outputs.exit_code }}
          SAFARI=${{ steps.safari.outputs.exit_code }}

          if [[ "$CHROME" != "0" || "$FIREFOX" != "0" || "$EDGE" != "0" || "$SAFARI" != "0" ]]
          then
            exit 1
          fi


# TODO: build publish to surge
