name: End to End Tests on PR

on:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.3.4
      # Needed to be able to run `npm ci`. It fails if we try to install libraries from a github repo
      # e.g. "wpt": "git+https://github.com/Woopra/browser-tracker.git#v5.1.20",

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      #- name: Install Docker
      #  run: brew install --cask docker

      #- name: Open Docker
      #  run: /Applications/Docker.app/Contents/MacOS/Docker &

      #- name: Create Docker alias
      #  run: alias docker='/Applications/Docker.app/Contents/Resources/bin/docker'

      #- name: Run Docker alias
      #  run: docker

      #- name: List contents of /usr/local/bin
      #  run: ls -la /usr/local/bin

      #- name: Install Dependencies
      #  run: npm install

      #- name: Run build
      #  run: npm run build:test
      - name: Install basic pre-reqs
        run: npm install -g babel-cli

      - name: Run e2e tests on Chrome, Firefox and Safari (local)
        run: npm run test:e2e:local
