name: Mock server in Docker

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run:
          docker build ./test/mock-server/ --file ./test/mock-server/Dockerfile --tag stefaniacardenas/onfido-web-sdk:latest